import java.io.*;
import java.sql.*;
import java.util.Properties;

public class DatabaseManager {

    private static Connection connection = null;
    private static final String CONFIG_FILE = "db_config.properties";

    public static class DbConfig {
        public String host = "localhost";
        public String port = "1521";
        public String service = "XEPDB1";
        public String username = "system";
        public String password = "";
        public boolean remember = true;
    }

    public static synchronized Connection getConnection() {
        return connection;
    }

    public static synchronized void setConnection(Connection conn) {
        connection = conn;
    }

    public static synchronized boolean isConnected() {
        try {
            return connection != null && !connection.isClosed();
        } catch (SQLException e) {
            return false;
        }
    }

    public static synchronized void closeConnection() {
        if (connection != null) {
            try {
                connection.close();
            } catch (SQLException ignored) {
            }
            connection = null;
        }
    }

    public static String buildJdbcUrl(String host, String port, String service) {
        return "jdbc:oracle:thin:@" + host.trim() + ":" + port.trim() + "/" + service.trim();
    }

    public static Connection establishConnection(String host, String port, String service, String user, String pass) throws Exception {
        Class.forName("oracle.jdbc.OracleDriver");
        String url = buildJdbcUrl(host, port, service);
        DriverManager.setLoginTimeout(8); // 8 seconds timeout
        Connection conn = DriverManager.getConnection(url, user.trim(), pass);
        return conn;
    }

    public static DbConfig loadConfig() {
        DbConfig config = new DbConfig();
        File file = new File(CONFIG_FILE);
        if (file.exists()) {
            try (InputStream in = new FileInputStream(file)) {
                Properties props = new Properties();
                props.load(in);
                config.host = props.getProperty("db.host", "localhost");
                config.port = props.getProperty("db.port", "1521");
                config.service = props.getProperty("db.service", "XEPDB1");
                config.username = props.getProperty("db.username", "system");
                config.password = props.getProperty("db.password", "");
                config.remember = Boolean.parseBoolean(props.getProperty("db.remember", "true"));
            } catch (Exception ignored) {
            }
        }
        return config;
    }

    public static void saveConfig(DbConfig config) {
        try (OutputStream out = new FileOutputStream(CONFIG_FILE)) {
            Properties props = new Properties();
            props.setProperty("db.host", config.host);
            props.setProperty("db.port", config.port);
            props.setProperty("db.service", config.service);
            props.setProperty("db.username", config.username);
            if (config.remember) {
                props.setProperty("db.password", config.password);
                props.setProperty("db.remember", "true");
            } else {
                props.setProperty("db.password", "");
                props.setProperty("db.remember", "false");
            }
            props.store(out, "LMS Database Configuration");
        } catch (Exception e) {
            System.err.println("Could not save config: " + e.getMessage());
        }
    }

    public static void initializeSchema(Connection conn) {
        String createBooks = "CREATE TABLE BOOKS ("
                + "BOOK_ID NUMBER GENERATED BY DEFAULT AS IDENTITY, "
                + "TITLE VARCHAR2(100) NOT NULL, "
                + "AUTHOR VARCHAR2(100) NOT NULL, "
                + "ISBN VARCHAR2(20) NOT NULL, "
                + "CATEGORY VARCHAR2(50) NOT NULL, "
                + "PUBLICATION_YEAR NUMBER(4), "
                + "SHELF_LOCATION VARCHAR2(20) NOT NULL, "
                + "STATUS VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL, "
                + "CONSTRAINT PK_BOOKS PRIMARY KEY (BOOK_ID), "
                + "CONSTRAINT UK_BOOKS_ISBN UNIQUE (ISBN), "
                + "CONSTRAINT CHK_BOOK_STATUS CHECK (STATUS IN ('AVAILABLE', 'ISSUED')), "
                + "CONSTRAINT CHK_PUBLICATION_YEAR CHECK (PUBLICATION_YEAR >= 1000))";

        String createMembers = "CREATE TABLE MEMBERS ("
                + "MEMBER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY, "
                + "NAME VARCHAR2(100) NOT NULL, "
                + "USERNAME VARCHAR2(30) NOT NULL, "
                + "PASSWORD VARCHAR2(256) NOT NULL, "
                + "ROLE VARCHAR2(10) NOT NULL, "
                + "EMAIL VARCHAR2(100) NOT NULL, "
                + "PHONE VARCHAR2(10) NOT NULL, "
                + "BOOKISSUED NUMBER(2) DEFAULT 0, "
                + "CONSTRAINT PK_MEMBERS PRIMARY KEY (MEMBER_ID), "
                + "CONSTRAINT UK_MEMBER_USERNAME UNIQUE (USERNAME), "
                + "CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL), "
                + "CONSTRAINT UK_MEMBER_PHONE UNIQUE (PHONE))";

        String createTransactions = "CREATE TABLE TRANSACTIONS ("
                + "TRANSACTION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY, "
                + "BOOK_ID NUMBER NOT NULL, "
                + "MEMBER_ID NUMBER NOT NULL, "
                + "ISSUE_DATE DATE NOT NULL, "
                + "RETURN_DATE DATE, "
                + "RETURNED CHAR(1) DEFAULT 'N' NOT NULL, "
                + "CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID), "
                + "CONSTRAINT FK_TRANSACTION_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID), "
                + "CONSTRAINT FK_TRANSACTION_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID), "
                + "CONSTRAINT CHK_RETURNED CHECK (RETURNED IN ('Y','N')))";

        try (Statement stmt = conn.createStatement()) {
            executeTableCreate(stmt, createBooks, "BOOKS");
            executeTableCreate(stmt, createMembers, "MEMBERS");
            executeTableCreate(stmt, createTransactions, "TRANSACTIONS");
            ensureDefaultAdmin(conn);
        } catch (SQLException e) {
            System.err.println("Schema initialization error: " + e.getMessage());
        }
    }

    private static void executeTableCreate(Statement stmt, String sql, String tableName) {
        try {
            stmt.executeUpdate(sql);
            System.out.println("Table " + tableName + " created successfully.");
        } catch (SQLException e) {
            // ORA-00955: name is already used by an existing object
            if (e.getErrorCode() == 955 || e.getMessage().toLowerCase().contains("already exists")) {
                System.out.println("Table " + tableName + " already exists.");
            } else {
                System.err.println("Warning creating table " + tableName + ": " + e.getMessage());
            }
        }
    }

    private static void ensureDefaultAdmin(Connection conn) {
        String checkAdmin = "SELECT COUNT(*) FROM MEMBERS WHERE USERNAME = 'admin'";
        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(checkAdmin)) {
            if (rs.next() && rs.getInt(1) == 0) {
                String hashed = PasswordUtil.hashPassword("admin");
                String insertAdmin = "INSERT INTO MEMBERS(NAME, USERNAME, PASSWORD, ROLE, EMAIL, PHONE, BOOKISSUED) "
                        + "VALUES ('System Administrator', 'admin', ?, 'ADMIN', 'admin@library.io', '9876543210', 0)";
                try (PreparedStatement ps = conn.prepareStatement(insertAdmin)) {
                    ps.setString(1, hashed);
                    ps.executeUpdate();
                    System.out.println("Default admin user created: admin / admin");
                }
            }
        } catch (Exception e) {
            System.err.println("Notice: admin check/creation: " + e.getMessage());
        }
    }
}

