
import java.sql.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Scanner;

public class Main {

    private static final String url = "jdbc:oracle:thin:@localhost:1521/XEPDB1";
    // For Oracle XE 21c/18c

    private static final String username = "system";
    private static final String password = "soumi";

    public static void main(String[] args) {

        Connection connection = null;
        Statement statement = null;

        try {
            // Load Oracle JDBC Driver
            Class.forName("oracle.jdbc.OracleDriver");

            // Establish Connection
            connection = DriverManager.getConnection(url, username, password);

            statement = connection.createStatement();

            // ResultSet rs = statement.executeQuery("SELECT USER FROM dual");
            //
            // while (rs.next()) {
            // System.out.println("Connected as: " + rs.getString(1));
            // }
            String query = "CREATE TABLE BOOKS (BOOK_ID NUMBER GENERATED BY DEFAULT AS IDENTITY, TITLE VARCHAR2(100) NOT NULL, AUTHOR VARCHAR2(100) NOT NULL, ISBN VARCHAR2(20) NOT NULL, CATEGORY VARCHAR2(50) NOT NULL, PUBLICATION_YEAR NUMBER(4), SHELF_LOCATION VARCHAR2(20) NOT NULL, STATUS VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,CONSTRAINT PK_BOOKS PRIMARY KEY (BOOK_ID), CONSTRAINT UK_BOOKS_ISBN UNIQUE (ISBN), CONSTRAINT CHK_BOOK_STATUS CHECK (STATUS IN ('AVAILABLE', 'ISSUED')), CONSTRAINT CHK_PUBLICATION_YEAR CHECK (PUBLICATION_YEAR >= 1000))";

            ResultSet rs = statement.executeQuery(query);

            // while (rs.next()) {
            // int id = rs.getInt("id");
            // String name = rs.getString("name");
            // int age = rs.getInt("age");
            // double marks = rs.getDouble("marks");
            // System.out.println("ID: " + id);
            // System.out.println("Name: " + name);
            // System.out.println("Age: " + age);
            // System.out.println("Marks: " + marks);
            // System.out.println("----------------------");
            // }
            rs.close();
            // statement.close();
            // connection.close();

        } catch (ClassNotFoundException e) {
            System.out.println("Driver not found!");
        } catch (SQLException e) {
            // System.out.println(e.getMessage());
            System.out.println("databse already exists. not created again");

        }

        try {
            // Load Oracle JDBC Driver
            Class.forName("oracle.jdbc.OracleDriver");

            // Establish Connection
            // connection = DriverManager.getConnection(url, username, password);

            statement = connection.createStatement();

            // ResultSet rs = statement.executeQuery("SELECT USER FROM dual");
            //
            // while (rs.next()) {
            // System.out.println("Connected as: " + rs.getString(1));
            // }
            String query = "CREATE TABLE MEMBERS (\n"
                    + "MEMBER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,\n"
                    + "NAME VARCHAR2(100) NOT NULL,\n"
                    + "USERNAME VARCHAR2(30) NOT NULL,\n"
                    + "PASSWORD VARCHAR2(256) NOT NULL,\n"
                    + "ROLE VARCHAR2(10) NOT NULL,\n"
                    + "EMAIL VARCHAR2(100) NOT NULL,\n"
                    + "PHONE VARCHAR2(10) NOT NULL,\n"
                    + "BOOKISSUED NUMBER(2) DEFAULT 0,\n"
                    + "CONSTRAINT PK_MEMBERS PRIMARY KEY (MEMBER_ID),\n"
                    + "CONSTRAINT UK_MEMBER_USERNAME UNIQUE (USERNAME),\n"
                    + "CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL),\n"
                    + "CONSTRAINT UK_MEMBER_PHONE UNIQUE (PHONE))";

            // System.out.println(query);
            ResultSet rs = statement.executeQuery(query);

            // while (rs.next()) {
            // int id = rs.getInt("id");
            // String name = rs.getString("name");
            // int age = rs.getInt("age");
            // double marks = rs.getDouble("marks");
            // System.out.println("ID: " + id);
            // System.out.println("Name: " + name);
            // System.out.println("Age: " + age);
            // System.out.println("Marks: " + marks);
            // System.out.println("----------------------");
            // }
            rs.close();
            // statement.close();
            // connection.close();

        } catch (ClassNotFoundException e) {
            System.out.println("Driver not found!");
        } catch (SQLException e) {
            // System.out.println(e.getMessage());
            System.out.println("databse already exists. not created again");

        }

        try {
            // Load Oracle JDBC Driver
            Class.forName("oracle.jdbc.OracleDriver");

            // Establish Connection
            // connection = DriverManager.getConnection(url, username, password);
            //
            statement = connection.createStatement();

            // ResultSet rs = statement.executeQuery("SELECT USER FROM dual");
            //
            // while (rs.next()) {
            // System.out.println("Connected as: " + rs.getString(1));
            // }
            String query = "CREATE TABLE TRANSACTIONS (\n"
                    + "TRANSACTION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,\n"
                    + "BOOK_ID NUMBER NOT NULL,\n"
                    + "MEMBER_ID NUMBER NOT NULL,\n"
                    + "ISSUE_DATE DATE NOT NULL,\n"
                    + "RETURN_DATE DATE,\n"
                    + "RETURNED CHAR(1) DEFAULT 'N' NOT NULL,\n"
                    + "CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID),\n"
                    + "CONSTRAINT FK_TRANSACTION_BOOK\n"
                    + "FOREIGN KEY (BOOK_ID)\n"
                    + "REFERENCES BOOKS(BOOK_ID),\n"
                    + "CONSTRAINT FK_TRANSACTION_MEMBER\n"
                    + "FOREIGN KEY (MEMBER_ID)\n"
                    + "REFERENCES MEMBERS(MEMBER_ID),\n"
                    + "CONSTRAINT CHK_RETURNED\n"
                    + "CHECK (RETURNED IN ('Y','N')))";

            ResultSet rs = statement.executeQuery(query);

            // while (rs.next()) {
            // int id = rs.getInt("id");
            // String name = rs.getString("name");
            // int age = rs.getInt("age");
            // double marks = rs.getDouble("marks");
            // System.out.println("ID: " + id);
            // System.out.println("Name: " + name);
            // System.out.println("Age: " + age);
            // System.out.println("Marks: " + marks);
            // System.out.println("----------------------");
            // }
            rs.close();
            // statement.close();
            // connection.close();

        } catch (ClassNotFoundException e) {
            System.out.println("Driver not found!");
        } catch (SQLException e) {
            // System.out.println(e.getMessage());
            System.out.println("databse already exists. not created again");
        }

        Scanner sc = new Scanner(System.in);

        Library library = new Library();

        System.out.println("Login");

        System.out.print("Enter Username: ");
        String username = sc.next() + sc.nextLine();

        System.out.print("Enter Password: ");
        String password = sc.next();

        MemberDao memberDao = new MemberDao();

        Member member = memberDao.login(username, password, connection);

        if (member == null) {
            System.out.println("Invalid Username or Password");
            return;
        }
        System.out.println("Login Successful");
        System.out.println("Welcome " + member.getName());

        // Check role and open respective menu
        switch (member.getRole()) {

            case ADMIN:
                AdminMenu.show(connection, statement, sc, library, member);
                break;

            case LIBRARIAN:
                LibrarianMenu.show(connection, statement, sc, library, member);
                break;

            case STUDENT:
                StudentMenu.show(connection, statement, sc, library, member);
                break;

            default:
                System.out.println("Invalid role.");
        }
    }
}
