
import java.sql.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Scanner;

public class Main {

    private static final String url = "jdbc:oracle:thin:@localhost:1521/XEPDB1";
    // For Oracle XE 21c/18c

    private static final String username = "system";
    private static final String password = "soumi";

    public static void main(String[] args) {

        Connection connection = null;
        Statement statement = null;

        try {
            // Load Oracle JDBC Driver
            Class.forName("oracle.jdbc.OracleDriver");

            // Establish Connection
            connection = DriverManager.getConnection(url, username, password);

            statement = connection.createStatement();

//            ResultSet rs = statement.executeQuery("SELECT USER FROM dual");
//
//            while (rs.next()) {
//                System.out.println("Connected as: " + rs.getString(1));
//            }
            String query = "CREATE TABLE BOOKS (BOOK_ID NUMBER GENERATED BY DEFAULT AS IDENTITY, TITLE VARCHAR2(100) NOT NULL, AUTHOR VARCHAR2(100) NOT NULL, ISBN VARCHAR2(20) NOT NULL, CATEGORY VARCHAR2(50) NOT NULL, PUBLICATION_YEAR NUMBER(4), SHELF_LOCATION VARCHAR2(20) NOT NULL, STATUS VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,CONSTRAINT PK_BOOKS PRIMARY KEY (BOOK_ID), CONSTRAINT UK_BOOKS_ISBN UNIQUE (ISBN), CONSTRAINT CHK_BOOK_STATUS CHECK (STATUS IN ('AVAILABLE', 'ISSUED')), CONSTRAINT CHK_PUBLICATION_YEAR CHECK (PUBLICATION_YEAR >= 1000))";

            ResultSet rs = statement.executeQuery(query);

            //  while (rs.next()) {
            //  int id = rs.getInt("id");
            //  String name = rs.getString("name");
            //  int age = rs.getInt("age");
            //  double marks = rs.getDouble("marks");
            //  System.out.println("ID: " + id);
            //  System.out.println("Name: " + name);
            //  System.out.println("Age: " + age);
            //  System.out.println("Marks: " + marks);
            //  System.out.println("----------------------");
            //  }
            rs.close();
            statement.close();
            // connection.close();

        } catch (ClassNotFoundException e) {
            System.out.println("Driver not found!");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        try {
            // Load Oracle JDBC Driver
            Class.forName("oracle.jdbc.OracleDriver");

            // Establish Connection
            // connection = DriverManager.getConnection(url, username, password);

            statement = connection.createStatement();

//            ResultSet rs = statement.executeQuery("SELECT USER FROM dual");
//
//            while (rs.next()) {
//                System.out.println("Connected as: " + rs.getString(1));
//            }
            String query = "CREATE TABLE MEMBERS (\n"
                    + "MEMBER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,\n"
                    + "NAME VARCHAR2(100) NOT NULL,\n"
                    + "USERNAME VARCHAR2(30) NOT NULL,\n"
                    + "PASSWORD VARCHAR2(256) NOT NULL,\n"
                    + "ROLE VARCHAR2(10) NOT NULL,\n"
                    + "EMAIL VARCHAR2(100) NOT NULL,\n"
                    + "PHONE VARCHAR2(10) NOT NULL,\n"
                    + "BOOKISSUED NUMBER(2) DEFAULT 0,\n"
                    + "CONSTRAINT PK_MEMBERS PRIMARY KEY (MEMBER_ID),\n"
                    + "CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL),\n"
                    + "CONSTRAINT UK_MEMBER_PHONE UNIQUE (PHONE))";

            // System.out.println(query);
            ResultSet rs = statement.executeQuery(query);

            //  while (rs.next()) {
            //  int id = rs.getInt("id");
            //  String name = rs.getString("name");
            //  int age = rs.getInt("age");
            //  double marks = rs.getDouble("marks");
            //  System.out.println("ID: " + id);
            //  System.out.println("Name: " + name);
            //  System.out.println("Age: " + age);
            //  System.out.println("Marks: " + marks);
            //  System.out.println("----------------------");
            //  }
            rs.close();
            statement.close();
            // connection.close();

        } catch (ClassNotFoundException e) {
            System.out.println("Driver not found!");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        try {
            // Load Oracle JDBC Driver
            Class.forName("oracle.jdbc.OracleDriver");

            // Establish Connection
            // connection = DriverManager.getConnection(url, username, password);
// 
            statement = connection.createStatement();

//            ResultSet rs = statement.executeQuery("SELECT USER FROM dual");
//
//            while (rs.next()) {
//                System.out.println("Connected as: " + rs.getString(1));
//            }
            String query = "CREATE TABLE TRANSACTIONS (\n"
                    + "TRANSACTION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,\n"
                    + "BOOK_ID NUMBER NOT NULL,\n"
                    + "MEMBER_ID NUMBER NOT NULL,\n"
                    + "ISSUE_DATE DATE NOT NULL,\n"
                    + "RETURN_DATE DATE,\n"
                    + "RETURNED CHAR(1) DEFAULT 'N' NOT NULL,\n"
                    + "CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID),\n"
                    + "CONSTRAINT FK_TRANSACTION_BOOK\n"
                    + "FOREIGN KEY (BOOK_ID)\n"
                    + "REFERENCES BOOKS(BOOK_ID),\n"
                    + "CONSTRAINT FK_TRANSACTION_MEMBER\n"
                    + "FOREIGN KEY (MEMBER_ID)\n"
                    + "REFERENCES MEMBERS(MEMBER_ID),\n"
                    + "CONSTRAINT CHK_RETURNED\n"
                    + "CHECK (RETURNED IN ('Y','N')))";

            ResultSet rs = statement.executeQuery(query);

            //  while (rs.next()) {
            //  int id = rs.getInt("id");
            //  String name = rs.getString("name");
            //  int age = rs.getInt("age");
            //  double marks = rs.getDouble("marks");
            //  System.out.println("ID: " + id);
            //  System.out.println("Name: " + name);
            //  System.out.println("Age: " + age);
            //  System.out.println("Marks: " + marks);
            //  System.out.println("----------------------");
            //  }
            rs.close();
            statement.close();
            // connection.close();

        } catch (ClassNotFoundException e) {
            System.out.println("Driver not found!");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        Scanner sc = new Scanner(System.in);

        Library library = new Library();

        System.out.println("Login");

        System.out.print("Enter Username: ");
        String username = sc.next();

        System.out.print("Enter Password: ");
        String password = sc.next();

        MemberDao memberDao = new MemberDao();

        Member member = memberDao.login(username, password,connection);

        if (member == null) {
            System.out.println("Invalid Username or Password");
        } else {
            System.out.println("Login Successful");
            System.out.println("Welcome " + member.getName());

            // Check role and open respective menu
        }
        while (true) {
            System.out.println("\n===== LIBRARY MANAGEMENT SYSTEM =====");

            System.out.println("1. Add Book");
            System.out.println("2. Remove Book");
            System.out.println("3. View All Books");
            System.out.println("4. Search Book");
            System.out.println("5. Member Management");
            System.out.println("6. Issue Book");
            System.out.println("7. Return Book");
            System.out.println("8. View Transactions");
            System.out.println("9. Book Statistics");
            System.out.println("0. Exit");

            System.out.print("Enter Choice : ");

            int choice = sc.nextInt();
            sc.nextLine();

            switch (choice) {

                case 1: {
                    System.out.print("Enter Book ID : ");
                    int bookId = sc.nextInt();
                    sc.nextLine();

                    System.out.print("Enter Title : ");
                    String title = sc.nextLine();

                    System.out.print("Enter Author : ");
                    String author = sc.nextLine();

                    System.out.print("Enter ISBN : ");
                    String isbn = sc.nextLine();

                    System.out.print("Enter Category : ");
                    String category = sc.nextLine();

                    System.out.print("Enter Publication Year : ");
                    int year = sc.nextInt();
                    sc.nextLine();

                    System.out.print("Enter Shelf Location : ");
                    String shelf = sc.nextLine();

                    Book book = new Book(bookId, title, author, isbn, category, year, shelf);

                    // if (library.addBook(book)) {
                    //     System.out.println("Book Added Successfully.");
                    // } else {
                    //     System.out.println("Book ID Already Exists.");
                    // }
                    boolean result = BookDao.saveToDatabase(book, connection, statement);
                    System.out.println(result);
                    break;
                }
                case 2: {
                    System.out.print("Enter Book ID : ");
                    int bookId = sc.nextInt();

                    // if (library.removeBook(bookId)) {
                    //     System.out.println("Book Removed Successfully. ");
                    // } else {
                    //     System.out.println("Book Not Found.");
                    // }
                    boolean result = BookDao.removeBook(bookId, connection, statement);

                    if (result) {
                        System.out.println("Book Removed Successfully. ");
                    } else {
                        System.out.println("Book Not Found.");
                    }
                    break;
                }
                case 3: {
                    // library.viewAllBooks();
                    BookDao.viewAllBooks(connection, statement);
                    break;
                }
                case 4: {

                    System.out.println("\nSearch Book By");
                    System.out.println("1. Book ID");
                    System.out.println("2. Title");
                    System.out.println("3. ISBN");
                    System.out.println("4. Author");
                    System.out.println("5. Category");

                    System.out.print("Enter Choice : ");

                    int searchChoice = sc.nextInt();
                    sc.nextLine();

                    switch (searchChoice) {

                        case 1: {
                            System.out.print("Enter Book ID : ");
                            int bookId = sc.nextInt();
                            Book book = BookDao.searchBook(bookId, connection, statement);
                            if (book != null) {
                                book.displayBook();
                            } else {
                                System.out.println("Book Not Found.");
                            }
                            break;
                        }
                        case 2: {
                            System.out.print("Enter Title : ");
                            String title = sc.nextLine();
                            ArrayList<Book> books = BookDao.searchBooksByTitle(title, connection, statement);
                            library.displayBooks(books);
                            break;
                        }
                        case 3: {
                            System.out.print("Enter ISBN : ");
                            String isbn = sc.nextLine();
                            ArrayList<Book> books = BookDao.searchBooksByISBN(isbn, connection, statement);
                            library.displayBooks(books);
                            break;
                        }
                        case 4: {
                            System.out.print("Enter Author Name : ");
                            String author = sc.nextLine();
                            ArrayList<Book> books = BookDao.searchBooksByAuthor(author, connection, statement);
                            library.displayBooks(books);
                            break;
                        }
                        case 5: {
                            System.out.print("Enter Category : ");
                            String category = sc.nextLine();
                            ArrayList<Book> books = BookDao.searchBooksByCategory(category, connection, statement);
                            library.displayBooks(books);
                            break;
                        }
                        default:
                            System.out.println("Invalid Choice.");
                    }
                    break;
                }
                case 5: {
                    boolean memberMenu = true;

                    while (memberMenu) {

                        System.out.println("\n===== MEMBER MANAGEMENT =====");

                        System.out.println("1. Register Member");
                        System.out.println("2. View All Members");
                        System.out.println("3. Search Member");
                        System.out.println("4. Currently Borrowed Books");
                        System.out.println("5. Borrow History");
                        System.out.println("6. Calculate Fine");
                        System.out.println("0. Back");

                        System.out.print("Enter Choice : ");

                        int memberChoice = sc.nextInt();
                        sc.nextLine();

                        switch (memberChoice) {
                            case 1: {
                                System.out.print("Member ID : ");
                                int memberId = sc.nextInt();
                                sc.nextLine();

                                System.out.print("Name : ");
                                String name = sc.nextLine();

                                System.out.print("Email : ");
                                String email = sc.nextLine();

                                System.out.print("Phone : ");
                                String phone = sc.nextLine();
                                System.out.print("Username : ");
                                String username2 = sc.nextLine();
                                System.out.print("Password : ");
                                String password2 = sc.nextLine();
                                System.out.print("Role : ");
                                String role = sc.nextLine();

                                Member member2 = new Member(email, memberId, name, password2, phone, role.toUpperCase().equals("ADMIN") ? Role.ADMIN : role.toUpperCase().equals("LIBRARIAN") ? Role.LIBRARIAN : Role.STUDENT, username2);

                                // Member member = new Member(
                                //         memberId,
                                //         name,
                                //         email,
                                //         phone
                                // );
                                // if (library.registerMember(member)) {
                                //     System.out.println("Member Registered Successfully.");
                                // } else {
                                //     System.out.println("Member ID Already Exists.");
                                // }
                                member2.saveToDatabase(connection);
                                break;
                            }

                            case 2: {
                                boolean res = library.viewAllMembers(connection, statement);

                                System.out.println(res);
                                break;
                            }

                            case 3: {

                                System.out.print("Enter Member ID : ");

                                int memberId = sc.nextInt();

                                Member member3 = library.searchMember(memberId, connection, statement);

                                if (member3 != null) {
                                    member3.displayMember();
                                } else {
                                    System.out.println("Member Not Found.");
                                }
                                break;
                            }

                            case 4: {
                                System.out.print("Enter Member ID : ");
                                int memberId = sc.nextInt();
                                // library.viewBorrowedBooks(memberId);
                                TransactionDao.viewBorrowedBooks(memberId, connection, statement);
                                break;
                            }

                            case 5: {
                                System.out.println("Enter Member ID : ");
                                int memberId = sc.nextInt();
                                // library.viewBorrowHistory(memberId);
                                TransactionDao.viewBorrowHistory(memberId, connection, statement);
                                break;
                            }

                            case 6: {
                                System.out.print("Enter Member ID : ");
                                int memberId = sc.nextInt();
                                // library.calculateFine(memberId);
                                TransactionDao.calculateFine(memberId, connection, statement);
                                break;
                            }

                            case 0: {
                                memberMenu = false;
                                break;
                            }

                            default: {
                                System.out.println("Invalid Choice.");
                            }
                        }
                    }
                    break;
                }

                case 6: {

                    System.out.print("Enter Book ID : ");
                    int bookId = sc.nextInt();
                    sc.nextLine();

                    System.out.print("Enter Member ID : ");
                    int memberId = sc.nextInt();
                    sc.nextLine();

                    //System.out.print("Enter Issue Date (dd-mm-yyyy) : ");
                    LocalDate issueDate = LocalDate.now();

                    String message = TransactionDao.issueBook(
                            bookId,
                            memberId,
                            issueDate,
                            connection,
                            statement
                    );

                    System.out.println(message);

                    break;
                }

                case 7: {

                    System.out.print("Enter Book ID : ");
                    int bookId = sc.nextInt();
                    sc.nextLine();

                    // System.out.print("Enter Return Date (dd-mm-yyyy) : ");
                    // String returnDate = sc.nextLine();
                    LocalDate returnDate = LocalDate.now();

                    String message = TransactionDao.returnBook(
                            bookId,
                            returnDate,
                            connection,
                            statement
                    );

                    System.out.println(message);

                    break;
                }

                case 8: {
                    TransactionDao.viewAllTransactions(connection, statement);
                    break;
                }

                case 9: {
                    System.out.println("\n===== BOOK STATISTICS =====");
                    // library.countBooks();
                    // library.countAvailableBooks();
                    // library.countIssuedBooks();
                    System.out.println("Total Books : " + BookDao.countBooks(connection, statement));
                    System.out.println("Available Books : " + BookDao.countAvailableBooks(connection, statement));
                    System.out.println("Issued Books : " + BookDao.countIssuedBooks(connection, statement));
                    break;
                }

                case 0:
                    System.out.println("Thank You!");
                    return;

                default:
                    System.out.println("Invalid Choice.");

            }
        }

    }

}
